### ISSUE TITLE
Use js code editor for New function page

### ISSUE THREAD

**Issue by ahmedash95** [emad-elsaid/rubyfunctions#11]
It would be good to have [codemirror](https://codemirror.net/) as a text editor when adding a new function, Also, I can create a PR for it

![image](https://user-images.githubusercontent.com/8272048/78044496-0e822700-7375-11ea-88cb-a1d3cb3cacf6.png)

**Comment by emad-elsaid** [comment]
Yeah that would be nice to have, I'll wait for the PR man, thank you :heart:
