### ISSUE TITLE
Follow Button

### ISSUE THREAD

**Issue by AliOsm** [emad-elsaid/rubyfunctions#25]
# Problem

- Users can't follow each other.

# Suggested Solution

- Add Twitter like following mechanism to allow users to follow each other.

**Comment by emad-elsaid** [comment]
That's also a good feature, also one of the basic social feature, any idea about the implementation ?

**Comment by AliOsm** [comment]
I don't have a strong plan on how to implement this, but I'm thinking about one of the following packages:

- [acts_as_follower](https://rubygems.org/gems/acts_as_follower/versions/0.2.1)
- [socialization](https://rubygems.org/gems/socialization/versions/1.2.0)

What do you think?

**Comment by emad-elsaid** [comment]
Again this feature doesn't need gems to implement it, a simple implementation is a model for `follower, user` and that would be all

**Comment by AliOsm** [comment]
I like how you don't like to use gems in your projects :3
I will start developing this feature and make a pull request ASAP.

**Comment by emad-elsaid** [comment]
Nice, I recommend you open a draft pull request as soon as you have something, even just models, this way we can think together about the implementation
