### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by AliOsm** [emad-elsaid/rubyfunctions#26]
# Problem

- Users don't receive a comment notification when someone comment on their functions.

# Suggested Solution

- Add notification system to notify users about new comments, likes, new functions from followed users, ...

**Comment by emad-elsaid** [comment]
this is a good idea, one of the essential feature we should do
how do you think we can implement this?

**Comment by AliOsm** [comment]
I'm thinking about one of the following gems:

- [notifications](https://rubygems.org/gems/notifications/versions/0.0.5)
- [activity_notification](https://rubygems.org/gems/activity_notification)

What do you think?

**Comment by emad-elsaid** [comment]
The first gem is an engine, which is like including another application in your application, so I'll have to discard this one, the second one seems good.

But when I'm thinking about notifications I feel it's a basic feature that we don't need dependencies to implement it, I prefer to just build it ourselves, a simple notifications model, with a controller for `mark as read`, `mark all as read`, and some views. doesn't seem too complicated for implementation.
