### ISSUE TITLE
Setup Development Environment

### ISSUE THREAD

**Issue by a7madM** [emad-elsaid/rubyfunctions#27]
- Add development docker-compose file.
- Add development dockerfile to install development dependencies.
- Add Entrypoint shell script to handle rails boot up process.

**Comment by a7madM** [comment]
@emad-elsaid CC

**Comment by emad-elsaid** [comment]
I got the first two points but I didn't get the last one, what is the process you want to automate?

**Comment by a7madM** [comment]
- assets compile
- yarn check integrity
- check for database creation
- setup database(create db, load schema and execute migrations, run db:seed)

**Comment by abdoutelb** [comment]
#28
