### ISSUE TITLE
Check Ruby Code Syntax

### ISSUE THREAD

**Issue by a7madM** [emad-elsaid/rubyfunctions#31]
**Problem:** 
code field accepts any raw text
as it should at least accept only valid ruby code syntax wise

**Solution:**
Add Validation Method on function code field
that simulate ruby code in Ruby VM to test Syntax Validation.
it will raise an error if the code is invalid.

https://stackoverflow.com/questions/53379441/validate-ruby-syntax-using-ruby

**Comment by a7madM** [comment]
it will be something like this

![Screenshot from 2020-04-05 01-43-28](https://user-images.githubusercontent.com/7304788/78463593-ea10ac80-76de-11ea-88c2-ebebea977ef4.png)

**Comment by emad-elsaid** [comment]
fixed #21
