### ISSUE TITLE
Integrating DeepSource

### ISSUE THREAD

**Issue by abdoutelb** [emad-elsaid/rubyfunctions#38]
I saw new integration for hound. would you consider integrating deepsource (https://deepsource.io/)
as they released now for ruby code.They are check for alot of things (bug risks, anti-patterns, performance issues, security flaws (includes OWASP top 10)).

**Comment by emad-elsaid** [comment]
I added it here is the report 
https://deepsource.io/gh/emad-elsaid/rubyfunctions/

I'm not sure it's working, doesn't show up any indication that it recognizes the `src` directory content, and no issues at all, I'm either lucky or it didn't work

**Comment by abdoutelb** [comment]
I think is start working ... it ran on the last PR
https://deepsource.io/gh/emad-elsaid/rubyfunctions/run/61b657da-5659-4e2d-8e2a-65143b4a5edc/ruby

**Comment by emad-elsaid** [comment]
no, I got an email from their support, there is a bug and they'll rollout a fix for it, I didn't get ETA for it
