### ISSUE TITLE
Handle non saved user view

### ISSUE THREAD

**Issue by abdoutelb** [emad-elsaid/rubyfunctions#46]
If saves view for user not implemented yet, We can hide it for now 
it raised a server error.
ex: https://www.rubyfunctions.com/users/emad-elsaid/saves

**Comment by emad-elsaid** [comment]
it's a bug, this view were using the old partial name and I fixed it here: 
https://github.com/emad-elsaid/rubyfunctions/commit/22efed1766eee7f17b631a0737f3acb848404319
