### ISSUE TITLE
Can't know exactly the problem

### ISSUE THREAD

**Issue by mohamednaser** [emad-elsaid/rubyfunctions#47]
am trying to add a new function but an error message appeared don't let me know what the problem exactly.

find attachment 

![Ruby Functions](https://user-images.githubusercontent.com/6272923/79065609-0d74c200-7cb2-11ea-81c6-293718ccf7a1.png)

**Comment by emad-elsaid** [comment]
I think the issue here is that your code doesn't have a function, the idea is that each post you publish on this web app, is a function that does something useful.
